# Generated by Django 2.0.13 on 2019-06-27 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise4', '0002_auto_20190627_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ContactNo',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^\\d*$', 'Please Input you Contact Number.')]),
        ),
    ]
